on:
  push:
    branches:
      - sm
  pull_request:
    branches:
      - main
name: chart-releaser
jobs:
  helm-chart-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@users.noreply.github.com'
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true
      - name: Install helm unittests
        run: |
          helm env
          helm plugin install https://github.com/quintush/helm-unittest
      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.7.0
      - if: github.event_name == 'pull_request'
        name: Set target branch on pull_request
        run: |
          echo "TARGET_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
          echo "SINCE=HEAD" >> $GITHUB_ENV
      - if: github.event_name == 'push'
        name: Set target branch on push
        run: |
          echo "TARGET_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "SINCE=${{ github.event.before }}" >> $GITHUB_ENV
      - name: Create k8s Kind Cluster
        if: github.event_name == 'push'
        uses: helm/kind-action@v1.4.0
      - name: Install and test helm charts
        if: github.event_name == 'push'
        run: |
          for TEST_DIR in tests/ci/*
          do
            echo "Running test $(pwd)/${TEST_DIR}"
            ct install --target-branch ${{ env.TARGET_BRANCH }} --charts $(pwd)/${TEST_DIR}
          done      
      - name: Run an upgrade test
        if: github.event_name == 'push'
        run: |
          ct install --upgrade --target-branch main_copy
